### ISSUE TITLE
Cannot SetKeepAlive() on the tcp socket created by Dial() also true when using .UnderlyingConn() and type-asserting as net.TCPConn from net.Conn or tls.Conn object #765

### ISSUE THREAD

**Issue by andrewhodel** [gorilla/websocket#767] opened 2022-02-21 00:01 UTC
`UnderlyingConn().(*net.TCPConn).SetKeepAlive(bool)`

This is required currently to modify the TCP keep alive for a websocket created via golang gorilla Dial().

**Comment by garyburd** [comment] 2022-02-21 01:26
Duplicate of #765.

**Closed by garyburd** 2022-02-21 01:26 UTC
Labels: bug
