### ISSUE TITLE
Safari websocket compression is broken

### ISSUE THREAD

**Issue by mohamedmansour** [gorilla/websocket#731] opened 2021-10-21 15:48 UTC
Using go v1.17
Using gorilla websocket v1.4.2

iOS Safari 15 enabled by default for all users "NSURLSession WebSocket", by enabling this, it broke my application at (https://watchtheburn.com) if you have a Mac, you can inspect and see it not working (on an iOS device). 

Going into Experimental WebKit Features and disabling "NSURLSession WebSocket" it works again.

@ejain opened this up and closed it for #696 Any ideas how I can resolve it?

**Comment by garyburd** [comment] 2022-01-19 17:44
See [iOS 15 WKWebView websocket behaviour](https://developer.apple.com/forums/thread/685403), https://github.com/uNetworking/uWebSockets/issues/1347

**Comment by garyburd** [comment] 2022-09-17 15:17
Applications should disable compression when working with buggy Safari clients.  

There are reports that the problem is fixed in recent versions of Safari.

**Closed by garyburd** 2022-09-17 15:17 UTC
Labels: bug
