### ISSUE TITLE
[BUG] <title>panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by fanziyan** [gorilla/websocket#918] opened 2024-05-20 06:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A mutex has been used when writing data, but it still prompts [panic: concurrent write to websocket connection]。
![ws-panic](https://github.com/gorilla/websocket/assets/104851362/12dcac63-f29c-4905-bdb9-8c3dfdae699f)

### Expected Behavior

no panic happend

### Anything else?

https://github.com/gorilla/websocket/issues/913

**Comment by FZambia** [comment] 2024-05-20 08:40
Hello @fanziyan 

There were many issues like this in this repo. Usually it turns out that this panic helps to find concurrent write issues on early stages. And many issues were closed because users found the error in the app when they really concurrently writing to the WebSocket.

Having said that, please make sure it's the only usage of connection write in your app. Also, please provide a standalone reproducer if you made sure it's the only place and want the issue to be fixed. It's rather trivial to write the minimal reproducer and put some stress load on it to trigger the panic. But I guess you will find the mistake in your code while doing this.

**Comment by DpaziNN** [comment] 2024-05-20 19:53
This is probably because every time each goroutine calls the WriteJSON method, your mutex variable is copied, and the doc tells us that the mutex should not be copied after the first use. I had the same problem and I solved it by adding a mutex variable to the struct scope. In your case it might look like this
```Go
type GoViewConnection struct {
	viewWriteMutex sync.Mutex
	// other vars
}

func (c *GoViewConnection) WriteMessage(data []byte) error {
	c.viewWriteMutex.Lock()
	defer c.viewWriteMutex.Unlock()
	if c.Conn != nil {
		err := c.Conn.WriteMessage(messageType: 1, data)
		if err != nil {
			xwLog.LogByConfigAndLevel(model.ViewFuncModule+"WriteMessagetfl", logrus.InfoLevel)
			returnerr
		}
	}
	return nil
}
```

**Comment by nanoblackstone** [comment] 2024-05-23 01:09
Run [go vet](https://pkg.go.dev/cmd/vet) on the code. Run the application with the [race detector](https://go.dev/doc/articles/race_detector).  Let us know if the code panics after fixing all problems reported by `go vet` and the race detector.

**Comment by canelohill** [comment] 2024-07-06 16:30
The code in the screenshot uses a named argument syntax that Go does not have.  

Update the issue to show actual code.

**Comment by fanziyan** [comment] 2024-07-06 16:31
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jaitaiwan** [comment] 2024-07-08 13:21
Closing as #913 already touches this subject.

**Closed by jaitaiwan** 2024-07-08 13:21 UTC
Labels: bug
