### ISSUE TITLE
[question] tls-websocket connection fails "http: TLS handshake error from [...] : remote error: tls: unknown certificate"

### ISSUE THREAD

**Issue by Max-Beier** [gorilla/websocket#787] opened 2022-06-03 12:22 UTC
Hey everyone,

my problem is that my websocket connection fails everytime when a client (a svelte/node.js application running on a NGINX webserver) connects to my server. 

```go
func (s Server) Init() {
	s.Sessions = make(map[string]*Session)
	go http.HandleFunc("/", s.handler)
	err := http.ListenAndServeTLS(":4000", "tls/cert.pem","tls/key.pem" , nil)
	if err != nil {
		fmt.Println(err)
	}
}
```

"err" outputs: `http: TLS handshake error from [...] : remote error: tls: unknown certificate`

I'm using the same certificate that I created with letsencrypt on my NGINX webserver, that is used for a tls connection between webserver and browser. 
I believe it has something to do with my non-existent knowledge about tls certifcates. 

Thank you in advance!

## NGINX config

```nginx
server {

        root /home/ubuntu/actions-runner/_work/client/client/public;

        index index.html index.htm index.nginx-debian.html;
        server_name myserver.io www.myserver.io; # managed by Certbot


        location / {
                proxy_http_version 1.1; # FOR WEBSOCKET PROTOCOL 
                proxy_set_header Upgrade $http_upgrade; # FOR WEBSOCKET PROTOCOL 
                proxy_set_header Connection "upgrade"; # FOR WEBSOCKET PROTOCOL

                try_files $uri $uri/ =404;
        }


    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/myserver.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/myserver.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot



}server {
    if ($host = www.myserver.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = myserver.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80 ;
        listen [::]:80 ;
    server_name myserver.io www.myserver.io;
    return 404; # managed by Certbot




}
```

**Comment by garyburd** [comment] 2022-06-03 16:31
I am closing this issue because the problem is with http.ListenAndServeTLS or something it calls, not this package.

**Closed by garyburd** 2022-06-03 16:31 UTC
Labels: question
