### ISSUE TITLE
when I reconnect the connection，I recive the error “EOF”

### ISSUE THREAD

**Issue by ArlenFuCN** [gorilla/websocket#446] opened 2018-11-01 00:40 UTC
When I reconnect to the server with websocket,I recive the error “EOF”.
At that moment,I restarted the server.My client disconnect the connection and redial the server.And I recive the error.
this is my code:
```
for {
		conn, _, err := websocket.DefaultDialer.Dial(self.config.Url, nil)
		if err != nil {
			log.Printf("dial err:" + err.Error())
			log.Printf("wait 5 seconds to redial...")
			time.Sleep(time.Second * 5)
			continue
		}
		self.conn = conn
		break
	}
```
this is my log:
```
17:30:34.869419 client.go:657: wait 5 seconds to redial...                                                         
17:31:10.228998 client.go:657: dial err:EOF                                                                        
17:31:10.229263 client.go:657: wait 5 seconds to redial...                                                         
17:32:20.625053 main.go:16: dial err:EOF                                                                           
17:32:20.635352 main.go:16: wait 5 seconds to redial...                                                            
17:32:56.916856 main.go:16: dial err:EOF                                                                           
17:32:56.917122 main.go:16: wait 5 seconds to redial...                                                            
17:33:32.277380 main.go:16: dial err:EOF                                                                           
17:33:32.277647 main.go:16: wait 5 seconds to redial...                                                            
17:34:07.639108 main.go:16: dial err:EOF                                                             
17:34:07.639431 main.go:16: wait 5 seconds to redial...                                                            
17:34:42.999937 main.go:16: dial err:EOF                                                                           
17:34:43.000206 main.go:16: wait 5 seconds to redial...                                                            
17:35:18.204425 main.go:16: dial  err:EOF                                                                           
17:35:18.204691 main.go:16: wait 5 seconds to redial...                                                            
17:35:53.560229 main.go:16: dial err:EOF                                                                           
17:35:53.560533 main.go:16: wait 5 seconds to redial...                                                            
17:36:28.779919 main.go:16: dial  err:EOF                                                                           
17:36:28.780188 main.go:16: wait 5 seconds to redial...                                                            
17:37:03.967706 main.go:16: dial err:EOF                                                                           
17:37:03.968092 main.go:16: wait 5 seconds to redial...                                                            
17:37:57.310719 main.go:16: dial err:EOF                                                                           
17:37:57.311086 main.go:16: wait 5 seconds to redial...                                                            
17:38:31.298895 main.go:16: dial err:EOF                                                                           
17:38:31.299266 main.go:16: wait 5 seconds to redial...                                                            
17:38:33.226469 main.go:16: dial err:EOF                                                                           
17:38:33.226721 main.go:16: wait 5 seconds to redial...                                                            
17:38:46.980803 main.go:16: dial err:EOF                                                                           
17:38:46.981204 main.go:16: wait 5 seconds to redial...                                                            
17:39:06.590655 main.go:16: dial err:EOF                                                                           
17:39:06.590932 main.go:16: wait 5 seconds to redial...                                                            
17:39:08.580967 main.go:16: dial err:EOF                                    
```
I restart my client and machine.But I still recive this error.
I have seen lots of infomation in the internet.But I still don't know the reason about it.Is it useful to add "conn.Close()"?such as:
```
for {
		conn, _, err := websocket.DefaultDialer.Dial(self.config.Url, nil)
		if err != nil {
			log.Printf("dial err:" + err.Error())
			log.Printf("wait 5 seconds to redial...")
                        if conn!= nil {
                               conn.Close()
                        }
			time.Sleep(time.Second * 5)
			continue
		}
		self.conn = conn
		break
	}
```
I would appreciate your advice to handle this error.Thanks.

**Comment by stevenscott89** [comment] 2018-11-01 00:54
Assuming that the error is [io.EOF](https://godoc.org/io#EOF) and not some other error with the text "EOF", then the error is unexpected.  The expected error for EOF is [io.ErrUnexpectedEOF](https://godoc.org/io#ErrUnexpectedEOF).  Perhaps there should be a test for that.  This is a digression from your actual problem, so I'll move on.

It looks like the server is closing the connection for some reason. It's difficult to determine why from what's provided here.

If Dial returns an error, then there's no need to close the returned connection (it will be nil).

**Comment by stevenscott89** [comment] 2018-11-01 01:49
Run the client application with the [race detector](https://golang.org/doc/articles/race_detector.html) and report the results.

**Comment by ArlenFuCN** [comment] 2018-11-01 01:51
And I see the issue.It had mentioned the error."io.EOF"
[https://github.com/golang/go/issues/19874](url)
In this issue.I see this:
If the server closes the connection before handshake completes, net/tls returns a non-descriptive error "EOF".
I'm not sure if this is a problem with TLS or websocket.

**Comment by ArlenFuCN** [comment] 2018-11-01 01:53
Thanks for your reply.I will run the client with race detector.

**Comment by garyburd** [comment] 2018-11-14 20:37
Does the application work as expected with the first connection dialed?

**Comment by ArlenFuCN** [comment] 2018-11-16 01:15
> Does the application work as expected with the first connection dialed?

Yes.It worked as expected when first connect to the serve.It's normal.
This error occurred during reconnection or after disconnect.
It seldom happens.I'll keep watching about it to get more infomation.

**Comment by garyburd** [comment] 2018-11-16 01:29
At the package level, websocket connections are independent of each other.  The second connection dialed to a host is handled identically to the first. 

I am guessing that the problem is caused by one of the following:
- The server is rejecting connections, possibly due to rate limiting.
- The application does properly switch to the new connection.  The earlier suggestion about running the race detector is a good one.

I am closing this issue because there's insufficient information to reproduce the problem or diagnose what's going on. Please open an new issue if you can describe how we can reproduce the problem.

**Closed by garyburd** 2018-11-16 01:29 UTC
