### ISSUE TITLE
[question] How to close a connect correctly?

### ISSUE THREAD

**Issue by suerta-git** [gorilla/websocket#720] opened 2021-09-05 16:21 UTC
**Describe the problem you're having**

As I see, `conn.Close()` won't wait or send close message from/to peer. Does that mean if I only call `Close()` in server side to close a connnect, the peer will know nothing?

Sounds bad. What's the best way to close a connenct?

> pls answer this on both two cases of closing connect initiatively and passively

**Comment by elithrar** [comment] 2021-09-05 16:32
See this part of the docs: https://pkg.go.dev/github.com/gorilla/websocket#hdr-Control_Messages

> The default close handler sends a close message to the peer.

**Comment by elithrar** [comment] 2021-09-05 16:33
If you call Close() on the underlying connection, no message is sent to the peer, per the docs: https://pkg.go.dev/github.com/gorilla/websocket#Conn.Close￼

> Close closes the underlying network connection without sending or waiting for a close message.

**Comment by mamjsn** [comment] 2021-09-05 22:08
> Does that mean if I only call Close() in server side to close a connect, the peer will know nothing?

The peer will detect that the connection is closed.   

[Close code](https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.5) 1006 is used to report connection close w/o a close message.

Send a close message when you want to specify the code and reason reported to the peer application.  Wait for the echoed close message from the peer if want to wait for both peers to read all data before shutdown.

**Comment by suerta-git** [comment] 2021-09-06 05:51
Thanks your reply @elithrar @mamjsn . Here is my understanding, pls correct me if it's wrong:

**Case 1: When receiving a close message from peer (the peer raises closure)**

> The default close handler sends a close message to the peer.
> Returning a *CloseError from the NextReader, ReadMessage or the message Read method.

So we don't need to reply to peer by ourself, and the only thing we need to do is catching and dealing with the *CloseError.

Normally, we will close the Conn like this:

```golang
func readLoop(c *websocket.Conn) {
    for {
        mt, msg, err := c.NextReader()
        if err != nil {
            c.Close()  // Only close the connection without sending or waiting for a close message
            break
        }
    }
}
```

**Case 2:  When closing a connection actively**

> Close closes the underlying network connection without sending or waiting for a close message.

So we need to send a close message explicitly to peer by `c.WriteControl()`, and wait for a close message response from peer then go to case 1. And maybe the deadline is necessary to time out the closure.

**Comment by suerta-git** [comment] 2021-09-06 05:55
> > Does that mean if I only call Close() in server side to close a connect, the peer will know nothing?
> 
> The peer will detect that the connection is closed.

@mamjsn But I am confused why the peer can detect this if the `Close()` method won't send a close message to peer.

**Comment by mamjsn** [comment] 2021-09-07 07:26
> But I am confused why the peer can detect this if the Close() method

Close() initiates connection termination at the TCP layer.  The peer's TCP stack will report the termination to the peer's application in some way.  In Go, the TCP connection methods return an error when the connection is terminated.

Ask the following questions for scenario your scenario 2:

1. Do you want to specify the close code and reason reported to the peer application?
2. Do you want a "clean" close?  In a clean close, it's possible to read all messages written by the peer.  If it's OK to ignore a message written by the peer, then you don't need a clean close.

The algorithm for closing the connection is:

1. If the answer (1) or (2) is yes, then write a close message.
2. If the answer to (2) is yes, then wait (with a timeout) for the peer to respond with a close message. Process data messages while waiting for the close message.
3. Close the connection.

Step 3 alone is sufficient in many scenarios.  The addition of step 1 can aid with debugging.

**Comment by owaisrehman110** [comment] 2021-09-13 08:09
Hi Everyone,

I am having trouble while closing a connection from server side.
I am trying to close a websocket connection with a code (preferably a custom code) with along with a reason and also want a "clean close". This is my server side implementation in that regard. 

![image](https://user-images.githubusercontent.com/46837498/133045226-9e392ec7-2fac-4efe-af6e-850adf48c81a.png)

My Client side is a simple JS code.

![image](https://user-images.githubusercontent.com/46837498/133046424-841baff1-d36d-423d-9b52-bc1e96a513be.png)

The problem is that whenever "conn.WriteMessage()" get executed the client side calls onclose() method and code received there is always "1006" and "wasClean" is always false. This response is received on client side before conn.Close() is called.

I am new to this and also know that I have made some serious blunders in this implementation. Sorry for that in advance. 
Can anyone of you please correct the snippet that I have attached or guide me the steps to perform a "clean close" from server side?

**Closed** 2021-12-16 23:44 UTC
Labels: question

**Comment by xielei296** [comment] 2022-10-29 08:17
I checked the example, I'm very confucious about Close() methods due to it is called many times in the example, is it correct?

ref:
examples/command/main.go
