### ISSUE TITLE
Sometimes i got "unexpected reserved bits 0x40" with client of unity by BestHttp

### ISSUE THREAD

**Issue by spiderpoison** [gorilla/websocket#409] opened 2018-08-20 13:05 UTC
My Unity client with the lib of BestHttp. And on production env, server sometimes got err "unexpected reserved bits 0x40". I don't understand, please help me, thanks.

**Comment by stevenscott89** [comment] 2018-08-20 14:48
Possible duplicate of #366 and #373.  You may have a data race. Run the application with the race detector.

**Comment by spiderpoison** [comment] 2018-08-21 03:26
Whether is means server concurrent read or client concurrent write?

**Comment by elithrar** [comment] 2018-08-21 04:06
It means a reserved bit is being set incorrectly by the client -
https://tools.ietf.org/html/rfc6455#section-5.2 see the reserved bits
section here.

**Comment by stevenscott89** [comment] 2018-08-21 04:30
Issue #366 reports the same error message with concurrent readers on the server.

**Comment by spiderpoison** [comment] 2018-08-25 10:00
In QA environment, don't find any RACE of ReadMessage.
Is there any possible client send wrong data ?
or 
I will set RACE on production environment

**Comment by stevenscott89** [comment] 2018-08-25 14:02
Yes, it's also possible that a client sent bad data.

**Comment by spiderpoison** [comment] 2018-08-27 12:44
I had "unexpected reserved bits 0x40" with -race, but didn't have any DATA RACE.
So, maybe client send bad data...

**Comment by stevenscott89** [comment] 2018-08-28 14:48
If the compression extension is accepted, then newDecompressionReader is set to a non-nil value.

https://github.com/gorilla/websocket/blob/66b9c49e59c6c48f0ffce28c2d8b8a5678502c6d/server.go#L205-L208

https://github.com/gorilla/websocket/blob/66b9c49e59c6c48f0ffce28c2d8b8a5678502c6d/server.go#L225-L227

I noticed that the application can specify arbitrary handshake response headers and possibly accept the compression extension without Gorilla's knowledge.

@spiderpoison Does your application specify Sec-WebSocket-Extensions in the response header passed to Upgrader.Upgrade?

**Comment by stevenscott89** [comment] 2018-08-28 16:00
@spiderpoison I am asking about the response header passed to upgrader.Upgrade.  Is your application passing a response header to Upgrader.Upgrade? If so, does the header contain Sec-Websocket-Extensions?

**Comment by spiderpoison** [comment] 2018-08-29 02:07
My application don't pass response header to Upgrader.Upgrade.
It like this:
```
g.GET(uri, func(c *gin.Context) {
	func(w http.ResponseWriter, r *http.Request) {
		conn, err := wsupgrader.Upgrade(w, r, nil)
		if err != nil {
			....
		}
		.....
	}(c.Writer, c.Request)
})
```

**Comment by Benedicht** [comment] 2018-08-29 08:59
Gone through the `go get github.com/gorilla/websocket` and `go run server.go` steps for the echo sample. Fortunately I have an echo sample too, so it was quite easy to plug the two together. Also modified my sample to continuously send messages to the server.

I observed two things:

1. While my client tries to negotiate the compression extension, the server sends back no `Sec-WebSocket-Extensions` header.
2. Sent and received back more than 400 000 messages before stopped it, but seen no error.

**Comment by spiderpoison** [comment] 2018-08-29 12:16
https://github.com/gorilla/websocket/blob/66b9c49e59c6c48f0ffce28c2d8b8a5678502c6d/conn.go#L797-L805
What situation will c.newDecompressionReader == nil and (p[0]&rsv1Bit) != 0 ?

I have tried when client with compressing extension
If  Upgrader.EnableCompression = true then c.newDecompressionReader != nil and (p[0]&rsv1Bit) != 0
If Upgrader.EnableCompression = false then c.newDecompressionReader == nil and (p[0]&rsv1Bit) == 0

**Comment by garyburd** [comment] 2018-08-29 15:33
@Benedicht Thank you for looking at this. Please post the Sec-WebSocket-Extensions sent by your client so we can figure out why compression was not negotiated.

@spiderpoison If `c.newDecompressionReader == nil`, then compression was not negotiated.  If `(p[0]&rsv1Bit) != 0`,  then the peer sent a frame with the compression bit set.  If compression is not negotiated, then compressed frames are not allowed.

@spiderpoison Are clients other than  BestHTTP Unity3D plugin connecting to your server? I suggest logging the user agent on these errors.

**Comment by Benedicht** [comment] 2018-08-29 16:44
@garyburd Sorry, it was in my mind, but wrote my reply in a hurry.

So, here's the request that the plugin sends out:

```
GET ws://localhost:8080/echo HTTP/1.1
Host: localhost:8080
Upgrade: websocket
Connection: keep-alive, Upgrade
Sec-WebSocket-Key: AByVjQAZG+b4AAAAAKQKtQ==
Sec-WebSocket-Version: 13
Cache-Control: no-cache
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Accept-Encoding: gzip, identity
TE: identity
User-Agent: BestHTTP
Content-Length: 0
```

And the server's response:

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: +i0g6IcgMR6IT1j8zgZMfY7sqok=
```

**Comment by stevenscott89** [comment] 2018-09-10 02:47
Regarding compression negotiation:  The echo example does not enable compression.  If the handshake in the previous comment is from a connection to the echo example server, then the server response is as expected.

**Comment by garyburd** [comment] 2018-09-24 23:15
Closing because there's no response from OP in 26 days.

**Closed by garyburd** 2018-09-24 23:15 UTC
