### ISSUE TITLE
A server must not mask any frames that it sends to the client

### ISSUE THREAD

**Issue by dayadev** [gorilla/websocket#579] opened 2020-03-04 23:05 UTC
**Server**
```
upgrader := websocket.Upgrader{
		CheckOrigin: func(r *http.Request) bool { return true }}

	myConn, err := upgrader.Upgrade(w, r, nil)
```
It fails on the server at 
`
_, msg, err := myConn.ReadMessage()`

Client.js
`
var ws = new WebSocket("wss://wsapi.abc.com/ws/")`

I am having issues opening a connection as I get below error when trying to read message using 

**Error on client
`
WebSocket connection to 'wss://wsapi.abc.com/ws/' failed: A server must not mask any frames that it sends to the client.
`
**Error on the server**
 `close 1002 (protocol error): Masked frame from server`

**Comment by srybacki** [comment] 2020-03-05 00:23
The gorilla package does not mask frames sent from a server to a client.

Here's a wild guess on what the issue is:  the data on the network is garbled because the application makes concurrent calls to the write methods. Run the application with [race detector](https://golang.org/doc/articles/race_detector.html) and fix any issues.

**Comment by elithrar** [comment] 2020-04-28 19:06
Closing out for now, but let us know if any follow-up questions.

**Closed** 2020-04-28 19:06 UTC
Labels: question
