### ISSUE TITLE
when client close connection server don't close connection in first time try to write in how to fix it without use ping pong 

### ISSUE THREAD

**Issue by ABD-ULZIZMAHMOUD** [gorilla/websocket#502] opened 2019-04-10 15:12 UTC

**Comment by stevenscott89** [comment] 2019-04-10 15:16
Possible duplicate of #226.

**Comment by ABD-ULZIZMAHMOUD** [comment] 2019-04-10 15:27
no in my case i used it to write only to client ,the possible solution is duplicate write to write empty massage than write write my message , first will close connection on server than get error on second . 
so can improve my solution to make function check connection to client and return true or false

**Comment by stevenscott89** [comment] 2019-04-10 15:40
As mentioned in 226, the first write to the underlying network connection after close does not return an error.  This is not something that can be fixed in this package.

> no in my case i used it to write only to client

The application is required to read the connection.  See [the control message documentation for more information](https://godoc.org/github.com/gorilla/websocket#hdr-Control_Messages).  

The application will quickly detect closed connections if the application reads the connection as required.

**Closed** 2019-04-10 15:45 UTC

**Comment by ABD-ULZIZMAHMOUD** [comment] 2019-04-10 15:47
thanks dear
