### ISSUE TITLE
ReadMessage return io.EOF error

### ISSUE THREAD

**Issue by cai-bf** [gorilla/websocket#790] opened 2022-06-16 08:15 UTC
Hello, I would like to ask, when I use ReadMessage, I get an io.EOF error. I drilled down to the code and found that there is only one place where this error is thrown, as shown in the image below.
<img width="950" alt="image" src="https://user-images.githubusercontent.com/33522016/174023471-7697e4a8-1f24-438a-aa35-842a64f07b57.png">
<img width="907" alt="image" src="https://user-images.githubusercontent.com/33522016/174024456-b7f75221-5a96-4b65-9ace-7f7651645460.png">
I can't understand why the payload of the previous frame is left behind, and `written < readRemaining` appears when discarded.
I want to know when this happens and why, this has brought me a lot of confusion, I sincerely hope you can give me some help.
thank you very much!

**Comment by easterf** [comment] 2022-06-16 16:14
There are a couple of possibilities: 
- The peer closed the connection before writing the advertised number of bytes to the network connection 
- The application has a data race. See [the doc on concurrency](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Concurrency).   Test your application with the [race detector](https://go.dev/doc/articles/race_detector).

**Comment by cai-bf** [comment] 2022-06-17 02:34
> There are a couple of possibilities:
> 
> * The peer closed the connection before writing the advertised number of bytes to the network connection
> * The application has a data race. See [the doc on concurrency](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Concurrency).   Test your application with the [race detector](https://go.dev/doc/articles/race_detector).
Thank you for your reply.
1. When the server receives an EOF error, the client is still trying to send heartbeat detection, so I assume it is not caused by the client closing the connection
2. I checked the code and confirmed that there was no data race
How else can I troubleshoot the problem?😭
Thanks so mush!

**Comment by easterf** [comment] 2022-06-17 03:36
Does the application using any method other than ReadMessage to read messages?  Did you run the race detector on the application?

**Comment by cai-bf** [comment] 2022-06-17 06:51
> Does the application using any method other than ReadMessage to read messages? Did you run the race detector on the application?
No, I only used a method of `Readmessage`, and also used the` race detector`, no risk was found

**Comment by amustaque97** [comment] 2022-06-19 16:47
@cai-bf , could you please share minimal code to reproduce the behaviour? Without going through the codebase it is difficult to debug and understand what is the real issue!?
> Use backticks `` to format code.

**Comment by cai-bf** [comment] 2022-06-20 02:41
> @cai-bf, could you please share minimal code to reproduce the behavior? Without going through the codebase it is difficult to debug and understand what the real issue is!?
> 
> > Use backticks `` to format code.

@amustaque97 OK, I'll post the key code below

**Comment by easterf** [comment] 2022-06-20 03:20
Are there any calls to h.conn.ReadMessage, h.conn.ReadJSON or h.conn.NextReader in the code not included here?

**Comment by cai-bf** [comment] 2022-06-20 03:43
> Are there any calls to h.conn.ReadMessage, h.conn.ReadJSON or h.conn.NextReader in the code not included here?

Only ReadMessage was called, and NextReader was called by ReadMessage

**Comment by easterf** [comment] 2022-06-20 04:50
Because `ReadMessage` reads the entire message (and any intervening control messages), I find it strange that `readRemaining` is greater than zero in `advanceFrame`.  Absent concurrent calls to the connection read methods, I don't see a scenario where ReadMessage returns with `readRemaining` greater than zero.

**Comment by cai-bf** [comment] 2022-06-20 06:17
> Because `ReadMessage` reads the entire message (and any intervening control messages), I find it strange that `readRemaining` is greater than zero in `advanceFrame`. Absent concurrent calls to the connection read methods, I don't see a scenario where ReadMessage returns with `readRemaining` greater than zero.

Yes, that's what I find strange. This is the only place in my code where 'ReadMessage' is called, which in theory should not be the case🤣

**Comment by easterf** [comment] 2022-06-20 16:18
Many applications use ReadMessage successfully. I don't see a way to reproduce the problem with the information provided.

What is the peer?  Perhaps the peer sends some sequence of frames that trips things up.

There's not an obvious problem with the code shown here.  Perhaps something is amiss in code not included.  For example, it will be a problem if h.upgrade.Upgrade invokes function argument in two goroutines.

**Comment by amustaque97** [comment] 2022-06-20 20:43
Yes, I agree with @easterf. With the given codebase `OnRead` method doesn't have any issue. I'm also not able to reproduce the error. It looks like an issue from the client-side some data race condition or some sort of leak.

**Comment by amustaque97** [comment] 2022-06-24 18:22
Hi @cai-bf :wave: were you able to fix the issue? If yes, can we close the issue?

**Comment by garyburd** [comment] 2022-07-12 15:38
It looks like an application data race. Closing because insufficient information to debug further.

**Closed by garyburd** 2022-07-12 15:38 UTC
