### ISSUE TITLE
error : read tcp x.x.x.x:8080->x.x.x.x:55992: i/o timeout with example chat

### ISSUE THREAD

**Issue by Jrmy2402** [gorilla/websocket#256] opened 2017-06-22 13:23 UTC
Hello,

I have an error with example chat: 

![capture d ecran_2017-06-22_15-18-03](https://user-images.githubusercontent.com/23458744/27436031-2f78634c-575e-11e7-9577-168f47efc772.png)

My code is:
```

package subscribe

import (
	"encoding/hex"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/websocket"
	"github.com/hectane/go-nonblockingchan"
)

const (
	// Time allowed to write a message to the peer.
	writeWait = 10 * time.Second

	// Time allowed to read the next pong message from the peer.
	pongWait = 60 * time.Second

	// Send pings to peer with this period. Must be less than pongWait.
	pingPeriod = (pongWait * 9) / 10

	// Maximum message size allowed from peer.
	maxMessageSize = 5012
)

var (
	idClient = 0
)

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
}

// Client is a middleman between the websocket connection and the hub.
type Client struct {
	hub *Hub

	// The websocket connection.
	conn *websocket.Conn

	// Buffered channel of outbound messages.
	channel *nbc.NonBlockingChan

	// Id of the client,
	id int

	// register subscribe by client
	Register *StructRegisterSubscribeClient
}

// readPump pumps messages from the websocket connection to the hub.
//
// The application runs readPump in a per-connection goroutine. The application
// ensures that there is at most one reader on a connection by executing all
// reads from this goroutine.
func (c *Client) readPump() {

	// unregister client and close connection if error
	defer func() {
		c.hub.unregister <- c
		c.conn.Close()
	}()

	// Set options of the connection
	c.conn.SetReadLimit(maxMessageSize)
	c.conn.SetReadDeadline(time.Now().Add(pongWait))
	c.conn.SetPongHandler(func(string) error {
		c.conn.SetReadDeadline(time.Now().Add(pongWait))
		fmt.Println("Receive Pong from server")
		return nil
	})

	// for infinite
	for {
		var msg MessageReceiveByWebsocket
		// Read in a new message as JSON and map it to a Message object
		err := c.conn.ReadJSON(&msg)
		log.Printf("Receive : %v", msg)
		// if err printf error in shell
		if err != nil {
			log.Printf("error : %v", err)
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway) {
				log.Printf("error : %v", err)
			}
			break
		}
		// Send message received to hub
		c.hub.subscribe <- &SendMessageReceiveToHub{messageReceive: msg, client: c}
	}
}

// writePump pumps messages from the hub to the websocket connection.
//
// A goroutine running writePump is started for each connection. The
// application ensures that there is at most one writer to a connection by
// executing all writes from this goroutine.
func (c *Client) writePump() {

	// Create NewTicker returns a new Ticker containing a channel that will send the time with a period specified
	ticker := time.NewTicker(pingPeriod)

	// stop ticker and close connection if error
	defer func() {
		ticker.Stop()
		c.conn.Close()
	}()

	// for infinite
	for {
		select {
		// receive message to send
		case message, ok := <-c.channel.Recv:

			// c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if !ok {
				// The hub closed the channel.
				c.conn.WriteMessage(websocket.CloseMessage, []byte{})
				return
			}
			// Encode value of message in hex
			encodedStr := hex.EncodeToString(message.(SendMessageHubToClient).Value)
			// Create message
			msg := &SendMessageToWebsocket{Type: "subscribeResponse", Name: c.Register.GetValueKey(message.(SendMessageHubToClient).Register), Content: ContentResponse{RegisterSubscribe: message.(SendMessageHubToClient).Register, Value: encodedStr}}
			// Send message
			c.conn.WriteJSON(msg)

		// Channel of ticker
		case <-ticker.C:

			// Set SetWriteDeadline
			c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if err := c.conn.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
				fmt.Println("Erro ici ", err)
				return
			}
		}
	}
}

// ServeWs handles websocket requests from the peer.
func ServeWs(hub *Hub, w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println(err)
		return
	}

	// increment idclient
	idClient = idClient + 1

	// Create new Client for connection
	client := &Client{hub: hub, conn: conn, channel: nbc.New(), id: idClient, Register: NewRegisterSubscribeClient()}

	// Registers the client with the hub
	client.hub.register <- client

	// Starts the client's writePump method as a goroutine
	go client.writePump()

	// Calls the client's readPump method.
	go client.readPump()
}
```

I write a lot message, about 300 messages every 30 milliseconds

**Comment by garyburd** [comment] 2017-06-22 15:23
The reader is timing out as the error states. Possible causes: overloaded client, overloaded  server, client is not sending pong in response to ping.

**Comment by Jrmy2402** [comment] 2017-06-22 17:26
I think it comes from an overload of my client... if I delete the Ping/Pong or increases WriteWait what is the risk?

**Comment by elithrar** [comment] 2017-06-22 17:41
a) If you delete the ping/pong, then you will be out of spec - clients
sending pings will not get a pong from you, and are likely to choose to
disconnect.
b) Increasing WriteWait -
https://godoc.org/github.com/gorilla/websocket#Conn.SetWriteDeadline - may
not address the issue - although it will give you more time to write to the
connection, the connection itself will still consume resources
(sockets/file descriptors).

300 messages every 30 milliseconds for a single client is certainly extreme
- how large is each message? Can you buffer messages into fewer but larger
payloads? Where is the client running? (browser? elsewhere?)

**Comment by Jrmy2402** [comment] 2017-06-22 19:26
Thanks for your reply, each message is a JSON of type SendMessageToWebsocket  
 `type DefineRegisterSubscribe struct {
	Register int `json:"register"`
	Size     int `json:"size"`
}
type ContentResponse struct {
	RegisterSubscribe DefineRegisterSubscribe `json:"register"`
	Value             string                  `json:"value"`
}
// SendMessageToWebsocket : defines our message to sent by websocket
type SendMessageToWebsocket struct {
	Type    string          `json:"type"`
	Name    string          `json:"name"`
	Content ContentResponse `json:"content"`
}`

My client is a node.js server that historizes all messages.

I will see to buffer the messages, but I would have liked to do without.

Do you think using a message broker like RabbitMq would be a better solution?

**Comment by elithrar** [comment] 2017-06-23 04:00
- What is the size of the message on the wire?
- How many connections does a single client open?
- Does this error occur with a single client and server or are you running
multiple clients?

The issue seems to be the client struggling to publish enough messages to
the socket and the server timing out waiting. Moving to another
application-level protocol is unlikely to solve this unless you can
understand the root cause.

**Comment by Jrmy2402** [comment] 2017-06-23 06:52
I do not know how to get the message size, but the TCP frames are of length 126-130.
The client opens a single connection and I have only one client and one server.
Yes I understand the root cause, I will try to improve my client so that he uses less resource

**Comment by Jrmy2402** [comment] 2017-06-23 12:49
I rewrote my client in golang with the Echo example, but I have a problem with the client because it does not respond to the server's ping, so the connection ends.

The client is not overloaded.

My code client: 

```
package main

import (
	"flag"
	"fmt"
	"log"
	"net/url"
	"os"
	"os/signal"
	"time"

	"github.com/gorilla/websocket"
)

// SendMessage is
var (
	addr        = flag.String("addr", "modbus:8080", "http service address")
	SendMessage = make(chan *MessageSendByWebsocket)
	count       = 0
)

// MessageSendByWebsocket : define our message Send by websocket
type MessageSendByWebsocket struct {
	Type    string                  `json:"type"`
	Name    string                  `json:"name"`
	Content DefineRegisterSubscribe `json:"content"`
}

// DefineRegisterSubscribe : define our registre to subscribe with register (is first octet to subscribe) and size (is number octet to subscribe)
type DefineRegisterSubscribe struct {
	Register int `json:"register"`
	Size     int `json:"size"`
}

// ContentResponse : define our Content response
type ContentResponse struct {
	RegisterSubscribe DefineRegisterSubscribe `json:"register"`
	Value             string                  `json:"value"`
}

// MessageReceiveByWebsocket : defines our message to sent by websocket
type MessageReceiveByWebsocket struct {
	Type    string          `json:"type"`
	Name    string          `json:"name"`
	Content ContentResponse `json:"content"`
}

func runWebSocket() {
	flag.Parse()
	log.SetFlags(0)

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)

	u := url.URL{Scheme: "ws", Host: *addr, Path: "/ws"}
	log.Printf("connecting to %s", u.String())

	c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
	if err != nil {
		log.Fatal("dial:", err)
	}
	defer c.Close()

	done := make(chan struct{})

	go func() {
		defer c.Close()
		defer close(done)
		for {
			var msg MessageReceiveByWebsocket
			err := c.ReadJSON(&msg)
			// log.Printf("Receive : %v", msg)
			if err != nil {
				log.Printf("error : %v", err)
				if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway) {
					log.Printf("error : %v", err)
				}
				break
			}
			count++
			if count%10000 == 0 {
				fmt.Println("Nombre de message reçu : ", count)
			}
			// log.Printf("recv: %s", message)
		}
	}()

	ticker := time.NewTicker(time.Second)
	defer ticker.Stop()

	for {
		select {
		case message := <-SendMessage:
			err2 := c.WriteJSON(message)
			if err2 != nil {
				log.Println("write:", err)
				return
			}
		case <-interrupt:
			log.Println("interrupt")
			// To cleanly close a connection, a client should send a close
			// frame and wait for the server to close the connection.
			err := c.WriteMessage(websocket.CloseMessage, websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
			if err != nil {
				log.Println("write close:", err)
				return
			}
			select {
			case <-done:
			case <-time.After(time.Second):
			}
			c.Close()
			return
		}
	}
}
```
My server code is always the same : 

```
package subscribe

import (
	"encoding/hex"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/websocket"
	"github.com/hectane/go-nonblockingchan"
)

const (
	// Time allowed to write a message to the peer.
	writeWait = 10 * time.Second

	// Time allowed to read the next pong message from the peer.
	pongWait = 60 * time.Second

	// Send pings to peer with this period. Must be less than pongWait.
	pingPeriod = (pongWait * 9) / 10

	// Maximum message size allowed from peer.
	maxMessageSize = 5012
)

var (
	idClient = 0
	count    = 0
)

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
}

// Client is a middleman between the websocket connection and the hub.
type Client struct {
	hub *Hub

	// The websocket connection.
	conn *websocket.Conn

	// Buffered channel of outbound messages.
	channel *nbc.NonBlockingChan

	// Id of the client,
	id int

	// register subscribe by client
	Register *StructRegisterSubscribeClient
}

// readPump pumps messages from the websocket connection to the hub.
//
// The application runs readPump in a per-connection goroutine. The application
// ensures that there is at most one reader on a connection by executing all
// reads from this goroutine.
func (c *Client) readPump() {

	// unregister client and close connection if error
	defer func() {
		c.hub.unregister <- c
		c.conn.Close()
	}()

	// Set options of the connection
	c.conn.SetReadLimit(maxMessageSize)
	c.conn.SetReadDeadline(time.Now().Add(pongWait))
	c.conn.SetPongHandler(func(string) error {
		c.conn.SetReadDeadline(time.Now().Add(pongWait))
		fmt.Println("Receive Pong")
		return nil
	})

	// for infinite
	for {
		var msg MessageReceiveByWebsocket
		// Read in a new message as JSON and map it to a Message object
		err := c.conn.ReadJSON(&msg)
		log.Printf("Receive : %v", msg)
		// if err printf error in shell
		if err != nil {
			log.Printf("error : %v", err)
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway) {
				log.Printf("error : %v", err)
			}
			break
		}
		// Send message received to hub
		c.hub.subscribe <- &SendMessageReceiveToHub{messageReceive: msg, client: c}
	}
}

// writePump pumps messages from the hub to the websocket connection.
//
// A goroutine running writePump is started for each connection. The
// application ensures that there is at most one writer to a connection by
// executing all writes from this goroutine.
func (c *Client) writePump() {

	// Create NewTicker returns a new Ticker containing a channel that will send the time with a period specified
	ticker := time.NewTicker(pingPeriod)

	// stop ticker and close connection if error
	defer func() {
		ticker.Stop()
		c.conn.Close()
	}()

	// for infinite
	for {
		select {
		// receive message to send
		case message, ok := <-c.channel.Recv:

			// c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if !ok {
				// The hub closed the channel.
				c.conn.WriteMessage(websocket.CloseMessage, []byte{})
				return
			}
			// Encode value of message in hex
			encodedStr := hex.EncodeToString(message.(SendMessageHubToClient).Value)
			// Create message
			msg := &SendMessageToWebsocket{Type: "subscribeResponse", Name: c.Register.GetValueKey(message.(SendMessageHubToClient).Register), Content: ContentResponse{RegisterSubscribe: message.(SendMessageHubToClient).Register, Value: encodedStr}}
			// Send message
			c.conn.WriteJSON(msg)
			count++
			if count%10000 == 0 {
				fmt.Println("Nombre de message reçu : ", count)
			}
		// Channel of ticker
		case <-ticker.C:

			// Set SetWriteDeadline
			c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if err := c.conn.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
				fmt.Println("Erro ici ", err)
				return
			}
		}
	}
}

// ServeWs handles websocket requests from the peer.
func ServeWs(hub *Hub, w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println(err)
		return
	}

	// increment idclient
	idClient = idClient + 1

	// Create new Client for connection
	client := &Client{hub: hub, conn: conn, channel: nbc.New(), id: idClient, Register: NewRegisterSubscribeClient()}

	// Registers the client with the hub
	client.hub.register <- client

	// Starts the client's writePump method as a goroutine
	go client.writePump()

	// Calls the client's readPump method.
	go client.readPump()
}

```

Error server after PongHandler: 

> write tcp 172.24.0.2:8080->172.24.0.8:50264: i/o timeout

> read tcp 172.24.0.2:8080->172.24.0.8:50264: use of closed network connection

**Comment by Jrmy2402** [comment] 2017-06-23 13:30
The error occurs if I send a message from the server to the client.
But if I do not send any message from the server to the client, the Ping and Pong goes well.

**Comment by elithrar** [comment] 2017-07-05 00:03
> I rewrote my client in golang with the Echo example, but I have a problem with the client because it does not respond to the server's ping, so the connection ends.

You should fix this first.

**Comment by garyburd** [comment] 2017-08-14 15:59
@Jrmy2402 Do you still have the problem after making the fix as suggested by elithrar?

**Closed** 2017-08-22 15:00 UTC
