### ISSUE TITLE
[question][feature] Add custom CONNECT header for proxy?

### ISSUE THREAD

**Issue by Fenny** [gorilla/websocket#559] opened 2019-12-10 15:11 UTC
Hello,

There are many proxy providers that use custom headers to authenticate or to rotate the proxy ip.
I'm wondering if I add the following code to [proxy.go Line 41-42](https://github.com/gorilla/websocket/blob/master/proxy.go#L41) would that be the right way to do it?
```go
connectHeader.Set("custom-proxy-header", "hi mom")
```
If so, maybe we could add this as an extra feature?

```go
dialer := websocket.Dialer{
  HandshakeTimeout: 10 * time.Second,
  Proxy: http.ProxyURL(&url.URL{
    Scheme:     "http",
    Host: 	"127.0.0.1:16969",
    Path: 	"/",
  }),
  ProxyHeaders: map[string]string{
    "custom-proxy-header": "hi mom",
  },
}
```
Thank you for all the help, I'm new to GO and the community is awesome :)

Duplicate [Issue 479](https://github.com/gorilla/websocket/issues/479)

**Comment by srybacki** [comment] 2019-12-10 15:54
The field should be `ProxyConnectHeader http.Header` to match the net/http `Transport` field. Other than that, this is a duplicate of 479.

**Comment by Fenny** [comment] 2019-12-10 20:42
@srybacki 

Could you help to implement this feature?

**Closed** 2020-01-15 04:45 UTC
Labels: question
