### ISSUE TITLE
Need some help to resolve the error: websocket: close 1006 (abnormal closure): unexpected EOF when logging into stdout

### ISSUE THREAD

**Issue by RachitKansal** [gorilla/websocket#447] opened 2018-11-05 13:25 UTC
Hi guys,

I have implemented the websockets using this library. Following is my config:
`writeWait = 15 * time.Second
pongWait = 60 * time.Second
pingPeriod = (pongWait * 8) / 10`

It is implemented similar to chat example.

Now I am stress testing my server where I have opened 1000 websocket connections. And pushing on an average 1 message each second to each of those connection. Now I hit the above issue when **only** when printing my logs to STDOUT (I am using a dockerised application and hence logging using the log.Println()). When I remove all the logs from my application, I never face the above issue. 

Am I missing something or doing something wrong here?, or do I need to make some optimisations?
Any suggestions would be greatly appreciated

**Comment by stevenscott89** [comment] 2018-11-09 14:36
There's not much to go on here. The first step is to determine why the connections are closed.  Is the hub closing the connection or the peer?   

As an aside, log.Println() goes to stderr by default, not stdout.

**Comment by garyburd** [comment] 2018-11-18 08:13
Closing because there's insufficient information to reproduce the problem and OP has not responded in over a week.

**Closed by garyburd** 2018-11-18 08:13 UTC
