### ISSUE TITLE
[bug] read tcp: read: connection reset by peer

### ISSUE THREAD

**Issue by rudyares** [gorilla/websocket#835] opened 2022-12-07 10:05 UTC
err:"read tcp: read: connection reset by peer" occurs too often when I call Conn.ReadMessage()

**Comment by chatmando** [comment] 2022-12-07 15:43
The "connection reset by peer" error typically indicates that the remote host unexpectedly closed the connection. This can be caused by a variety of factors, including network issues, or problems with the remote host. In some cases, the error may also be caused by a firewall blocking the connection. It's difficult to say exactly what the cause of the error is without more information.

**Comment by ayjayt** [comment] 2023-07-19 19:00
I like this project, maybe I'll start working on helping close old issues? Is that helpful?

This sounds more like a support request than a bug. There are lots of reasons the underlying tcp connections would be closer... any broken connection, any weird wire, etc. Without knowing anything about user's setup, you could maybe try increasing the number of Pings sent out.

**Comment by jaitaiwan** [comment] 2024-09-01 12:30
Thanks @ayjayt :)

Closing out

**Closed by jaitaiwan** 2024-09-01 12:30 UTC
Labels: bug
